### ISSUE TITLE
[Bug]: Color formatting tags don't parse

### ISSUE THREAD

**Issue by sisby-folk** [terrarium-earth/hercules#60]
### Bug Description

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/828942db-123f-4de7-845d-11644a5e5067)

### How to Reproduce?

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/bd7a493a-e89a-4245-92f3-4fea3c983e2f)

### Expected Behavior

The word "test" should appear in red.

### Version

1.0.3

### Mod Loader Version

1.20.1 - 0.19.2

### Mod Loader

Quilt

### Logs or additional context

idk if this should be reported to hermes instead but hey whatever

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Fixed

**Comment by sisby-folk** [comment]
Hello! this issue still occurs in 1.0.4, which seems to clash with the changelog
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/5577906c-8a74-48ee-a757-6685c22ca618)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/fa80f4cc-f88f-435f-9518-e4532cde75c9)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/f86287ce-29ad-4662-a915-a5eaca1c8918)

Home and end are working fine in this version, but this description still won't parse just yet! Thanks for looking into it so quickly though

**Comment by ThatGravyBoat** [comment]
send your logs

**Comment by ThatGravyBoat** [comment]
ok fixed it again I forgot that depending on the JVM the XML parsing implementation would be different resulting in different named XML entities existing and how XML entities were parsed, it now uses the most basic form which would work on all JVMs and OS if they properly support XML entity numbers
